<a href="https://colab.research.google.com/github/Ankushsb62/OASIS-INFOBYTE/blob/PROJECT-3/Cleaning_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np

In [ ]:
# Load the dataset
data = pd.read_csv('AB_NYC_2019.csv')
data.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,6.0,365.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,2.0,355.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,1.0,365.0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,1.0,194.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,1.0,0.0

In [ ]:
# Drop rows with missing values
data = data.dropna()
print(f'Number of rows after dropping missing values: {data.shape[0]}')

Number of rows after dropping missing values: 12413

In [ ]:
# Remove duplicate rows
data = data.drop_duplicates()
print(f'Number of rows after removing duplicates: {data.shape[0]}')

Number of rows after removing duplicates: 12413

In [ ]:
# Convert categorical variables to numerical using one-hot encoding
data = pd.get_dummies(data, columns=['room_type', 'neighbourhood_group', 'neighbourhood'])

# Print the column names after one-hot encoding
print(data.columns)

Index(['id', 'name', 'host_id', 'host_name', 'latitude', 'longitude', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       ...
       'neighbourhood_West Brighton', 'neighbourhood_West Farms',
       'neighbourhood_West Village', 'neighbourhood_Whitestone',
       'neighbourhood_Williamsbridge', 'neighbourhood_Williamsburg',
       'neighbourhood_Windsor Terrace', 'neighbourhood_Woodhaven',
       'neighbourhood_Woodlawn', 'neighbourhood_Woodside'],
      dtype='object', length=205)

In [ ]:
# Detect outliers using z-score
from scipy import stats
z_scores = np.abs(stats.zscore(data[['price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']]))
outliers = (z_scores > 3).any(axis=1)
data = data[~outliers]
print(f'Number of rows after removing outliers: {data.shape[0]}')

Number of rows after removing outliers: 11684

In [ ]:
# Save the cleaned dataset
data.to_csv('cleaned_dataset.csv', index=False)
print('Cleaned dataset saved as "cleaned_AB_NYC_2019.csv"')

Cleaned dataset saved as "cleaned_AB_NYC_2019.csv"